SELECT * FROM GOLD.CALENDAR;
SELECT * FROM GOLD.CUSTOMERS;
SELECT * FROM GOLD.PRODUCT_SUBCATEGORIES;
SELECT * FROM GOLD.PRODUCTS;
SELECT * FROM GOLD.RETURNS;
SELECT * FROM GOLD.SALES;
SELECT * FROM GOLD.TERRITORIES;